version: '3.9'

services:
  mongo:
    container_name: vet
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo.models
      MONGO_INITDB_ROOT_PASSWORD: mypass
    ports:
      - '27019:27017'
